Add purchase button & license-key settings
Emilia-Capital/progress-planner pull request #176
Opened 2024-12-10 11:08 UTC by aristath

## Context

*

## Summary

This PR can be summarized in the following changelog entry:

*

## Relevant technical choices:

*

## Test instructions

#### Relevant test scenarios
* [ ] Changes should be tested with the browser console open
* [ ] Changes should be tested on different posts/pages/taxonomies/custom post types/custom taxonomies
* [ ] Changes should be tested on different editors (Block/Classic/Elementor/other)
* [ ] Changes should be tested on different browsers
* [ ] Changes should be tested on multisite

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [ ] I have tested this code to the best of my abilities.
* [ ] I have added unit tests to verify the code works as intended.
* [ ] I have checked that the base branch is correctly set.

Fixes #

2024-12-14 18:43 UTC, jdevalk requested changes

2024-12-14 18:43 UTC, jdevalk commented on assets/css/page-widgets/get-pro.css
> +.get-pro-link {
This is basically a "normal" button right? Shouldn't the class name reflect that better?

2024-12-14 18:43 UTC, jdevalk commented on views/page-widgets/get-pro.php
> +<a class="get-pro-link" href="https://progressplanner.com/checkout/?edd_action=straight_to_gateway&download_id=1136" target="_blank">
We should make this a redirect / shortlink so that when we have to change anything we can...

2025-01-17 10:31 UTC, aristath commented
@jdevalk The "Get Pro" button was removed because it will be implemented as part of the challenges widget.
This PR is now limited to the license-key, and some CSS changes that will be needed for the new buttons in the challenges widget.

2025-01-17 11:02 UTC, jdevalk commented
Code LGTM - now testing functionally

2025-01-17 11:53 UTC, jdevalk requested changes

2025-01-17 11:53 UTC, jdevalk commented on views/admin-page-settings.php
> +									'<a href="https://progressplanner.com/pro" target="_blank">Progress Planner Pro</a>'
```suggestion
									'<a href="https://progressplanner.com/pro/" target="_blank">Progress Planner Pro</a>'
```

2025-01-17 11:53 UTC, jdevalk approved these changes

2025-01-17 11:55 UTC, merged